In [1]:
import tweepy
import os
import pandas as pd
consumer_key = "s4rhp108YWPsAnFi8RnEqLsTt"
consumer_secret = "83cqf4FhvX5t9Wpopep9uUCqskUIoMvE25Snou3BLM69I9BhUg"
access_token = "1259100090-KHRyNT9ck2PGKM66rwyZphjkgEntyluhnOVPIT9"
access_token_secret = "drKs4ZnLc9UNN32qEQ3Gm9P3kUrMGXE7jAYmRazYJggRA"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True)

# create list to append tweets to
tweets = []

# append all tweet data to list
for tweet in tweepy.Cursor(api.search, '#HudumaNumba', count=1000000).items():
    tweets.append(tweet)

# convert 'tweets' list to pandas.DataFrame
tweets_df = pd.DataFrame(vars(tweets[i]) for i in range(len(tweets)))

# define file path (string) to save csv file to
FILE_PATH = '/home/kip/Desktop/Sentiment-Analysis/HudumaNumb.txt'

# use pandas to save dataframe to csv
tweets_df.to_csv(FILE_PATH)
train = tweets_df
train.head(3)

,_api,_json,author,contributors,coordinates,created_at,entities,favorite_count,favorited,geo,...,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,retweeted_status,source,source_url,text,truncated,user
0,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sun Jul 21 06:25:08 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-21 06:25:08,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,1.152581e+18,1152581453617750017,3,False,Status(_api=<tweepy.api.API object at 0x7fe658...,Twitter for Android,http://twitter.com/download/android,RT @Miss_Diaspora: How we be dodging getting t...,False,User(_api=<tweepy.api.API object at 0x7fe65811...
1,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sun Jul 21 05:44:59 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-21 05:44:59,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,1.152581e+18,1152581453617750017,3,False,Status(_api=<tweepy.api.API object at 0x7fe658...,Twitter Web App,https://mobile.twitter.com,RT @Miss_Diaspora: How we be dodging getting t...,False,User(_api=<tweepy.api.API object at 0x7fe65811...
2,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sat Jul 20 18:37:33 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-20 18:37:33,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,1.152581e+18,1152581453617750017,3,False,Status(_api=<tweepy.api.API object at 0x7fe658...,Twitter Web App,https://mobile.twitter.com,RT @Miss_Diaspora: How we be dodging getting t...,False,User(_api=<tweepy.api.API object at 0x7fe65811...

In [2]:
# Number of Words
train['word_count'] = train['text'].apply(lambda x: len(str(x).split(" ")))
train[['text','word_count']].head()

                                                text  word_count
0  RT @Miss_Diaspora: How we be dodging getting t...          13
1  RT @Miss_Diaspora: How we be dodging getting t...          13
2  RT @Miss_Diaspora: How we be dodging getting t...          13
3  How we be dodging getting that shitty #huduman...          11
4  @Crazy_Nairobian How we be dodging getting tha...          11

In [3]:
# Number of characters
train['char_count'] = train['text'].str.len() ## this also includes spaces
train[['text','char_count']].head()

                                                text  char_count
0  RT @Miss_Diaspora: How we be dodging getting t...         102
1  RT @Miss_Diaspora: How we be dodging getting t...         102
2  RT @Miss_Diaspora: How we be dodging getting t...         102
3  How we be dodging getting that shitty #huduman...          83
4  @Crazy_Nairobian How we be dodging getting tha...          76

In [4]:
# Average Word Length
def avg_word(sentence):
  words = sentence.split()
  return (sum(len(word) for word in words)/len(words))

train['avg_word'] = train['text'].apply(lambda x: avg_word(x))
train[['text','avg_word']].head()

                                                text  avg_word
0  RT @Miss_Diaspora: How we be dodging getting t...  6.923077
1  RT @Miss_Diaspora: How we be dodging getting t...  6.923077
2  RT @Miss_Diaspora: How we be dodging getting t...  6.923077
3  How we be dodging getting that shitty #huduman...  6.636364
4  @Crazy_Nairobian How we be dodging getting tha...  6.000000

In [5]:
# Number of stopwords
from nltk.corpus import stopwords
stop = stopwords.words('english')

train['stopwords'] = train['text'].apply(lambda x: len([x for x in x.split() if x in stop]))
train[['text','stopwords']].head()

                                                text  stopwords
0  RT @Miss_Diaspora: How we be dodging getting t...          4
1  RT @Miss_Diaspora: How we be dodging getting t...          4
2  RT @Miss_Diaspora: How we be dodging getting t...          4
3  How we be dodging getting that shitty #huduman...          4
4  @Crazy_Nairobian How we be dodging getting tha...          4

In [6]:
# Number of special characters
train['hastags'] = train['text'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
train[['text','hastags']].head()

                                                text  hastags
0  RT @Miss_Diaspora: How we be dodging getting t...        1
1  RT @Miss_Diaspora: How we be dodging getting t...        1
2  RT @Miss_Diaspora: How we be dodging getting t...        1
3  How we be dodging getting that shitty #huduman...        1
4  @Crazy_Nairobian How we be dodging getting tha...        1

In [7]:
#  Number of numerics
train['numerics'] = train['text'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
train[['text','numerics']].head()

                                                text  numerics
0  RT @Miss_Diaspora: How we be dodging getting t...         0
1  RT @Miss_Diaspora: How we be dodging getting t...         0
2  RT @Miss_Diaspora: How we be dodging getting t...         0
3  How we be dodging getting that shitty #huduman...         0
4  @Crazy_Nairobian How we be dodging getting tha...         0

In [8]:
# Number of Uppercase words
train['upper'] = train['text'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
train[['text','upper']].head()

                                                text  upper
0  RT @Miss_Diaspora: How we be dodging getting t...      1
1  RT @Miss_Diaspora: How we be dodging getting t...      1
2  RT @Miss_Diaspora: How we be dodging getting t...      1
3  How we be dodging getting that shitty #huduman...      0
4  @Crazy_Nairobian How we be dodging getting tha...      0

In [9]:
# Lower case
train['text'] = train['text'].apply(lambda x: " ".join(x.lower() for x in x.split()))
train['text'].head()

0    rt @miss_diaspora: how we be dodging getting t...
1    rt @miss_diaspora: how we be dodging getting t...
2    rt @miss_diaspora: how we be dodging getting t...
3    how we be dodging getting that shitty #huduman...
4    @crazy_nairobian how we be dodging getting tha...
Name: text, dtype: object

In [10]:
# Removing Punctuation
train['text'] = train['text'].str.replace('[^\w\s]','')
train['text'].head()

0    rt miss_diaspora how we be dodging getting tha...
1    rt miss_diaspora how we be dodging getting tha...
2    rt miss_diaspora how we be dodging getting tha...
3    how we be dodging getting that shitty hudumanu...
4    crazy_nairobian how we be dodging getting that...
Name: text, dtype: object

In [11]:
#  Removal of Stop Words
from nltk.corpus import stopwords
stop = stopwords.words('english')
train['text'] = train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
train['text'].head()

0    rt miss_diaspora dodging getting shitty huduma...
1    rt miss_diaspora dodging getting shitty huduma...
2    rt miss_diaspora dodging getting shitty huduma...
3    dodging getting shitty hudumanumba gok httpstc...
4    crazy_nairobian dodging getting shitty huduman...
Name: text, dtype: object

In [12]:
# Common word removal
freq = pd.Series(' '.join(train['text']).split()).value_counts()[:10]
freq
# remove these words as their presence will not of any use in classification of our text data.
freq = list(freq.index)
train['text'] = train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
train['text'].head()

0    miss_diaspora httpstcouwjxyeyzg9
1    miss_diaspora httpstcouwjxyeyzg9
2    miss_diaspora httpstcouwjxyeyzg9
3                  httpstcouwjxyeyzg9
4                     crazy_nairobian
Name: text, dtype: object

In [13]:
# Rare words removal
freq = pd.Series(' '.join(train['text']).split()).value_counts()[-10:]
freq
freq = list(freq.index)
train['text'] = train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
train['text'].head()

0    miss_diaspora httpstcouwjxyeyzg9
1    miss_diaspora httpstcouwjxyeyzg9
2    miss_diaspora httpstcouwjxyeyzg9
3                  httpstcouwjxyeyzg9
4                     crazy_nairobian
Name: text, dtype: object

In [14]:
# Spelling correction
from textblob import TextBlob
train['text'][:5].apply(lambda x: str(TextBlob(x).correct()))

0    miss_diaspora httpstcouwjxyeyzg9
1    miss_diaspora httpstcouwjxyeyzg9
2    miss_diaspora httpstcouwjxyeyzg9
3                  httpstcouwjxyeyzg9
4                     crazy_nairobian
Name: text, dtype: object

In [15]:
# Stemming
from nltk.stem import PorterStemmer
st = PorterStemmer()
train['text'][:5].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

0    miss_diaspora httpstcouwjxyeyzg9
1    miss_diaspora httpstcouwjxyeyzg9
2    miss_diaspora httpstcouwjxyeyzg9
3                  httpstcouwjxyeyzg9
4                     crazy_nairobian
Name: text, dtype: object

In [16]:
train.head(3)

,_api,_json,author,contributors,coordinates,created_at,entities,favorite_count,favorited,geo,...,text,truncated,user,word_count,char_count,avg_word,stopwords,hastags,numerics,upper
0,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sun Jul 21 06:25:08 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-21 06:25:08,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,miss_diaspora httpstcouwjxyeyzg9,False,User(_api=<tweepy.api.API object at 0x7fe65811...,13,102,6.923077,4,1,0,1
1,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sun Jul 21 05:44:59 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-21 05:44:59,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,miss_diaspora httpstcouwjxyeyzg9,False,User(_api=<tweepy.api.API object at 0x7fe65811...,13,102,6.923077,4,1,0,1
2,<tweepy.api.API object at 0x7fe65811ce10>,{'created_at': 'Sat Jul 20 18:37:33 +0000 2019...,User(_api=<tweepy.api.API object at 0x7fe65811...,None,None,2019-07-20 18:37:33,"{'hashtags': [{'text': 'hudumanumba', 'indices...",0,False,None,...,miss_diaspora httpstcouwjxyeyzg9,False,User(_api=<tweepy.api.API object at 0x7fe65811...,13,102,6.923077,4,1,0,1

In [17]:
list(train.columns)

['_api',
 '_json',
 'author',
 'contributors',
 'coordinates',
 'created_at',
 'entities',
 'favorite_count',
 'favorited',
 'geo',
 'id',
 'id_str',
 'in_reply_to_screen_name',
 'in_reply_to_status_id',
 'in_reply_to_status_id_str',
 'in_reply_to_user_id',
 'in_reply_to_user_id_str',
 'is_quote_status',
 'lang',
 'metadata',
 'place',
 'possibly_sensitive',
 'quoted_status',
 'quoted_status_id',
 'quoted_status_id_str',
 'retweet_count',
 'retweeted',
 'retweeted_status',
 'source',
 'source_url',
 'text',
 'truncated',
 'user',
 'word_count',
 'char_count',
 'avg_word',
 'stopwords',
 'hastags',
 'numerics',
 'upper']

In [ ]:
data = pd.DataFrame(train[['created_at','text','word_count','char_count','avg_word','stopwords','hastags','numerics','upper','tweet']])
data.head(3)

In [ ]:
# define file path (string) to save csv file to
FILE_PATH = '/home/kip/Desktop/Sentiment-Analysis/HudumaNumb.csv'

# use pandas to save dataframe to csv
data.to_csv(FILE_PATH)